// Copyright (c) 2024-2026 ThreatEcho. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-only
// https://threatecho.com

package report

import (
	"fmt"
	"io"
	"strings"

	"github.com/ThreatEcho/threatecho/internal/gap"
	"github.com/ThreatEcho/threatecho/pkg/version"
)

// GapMarkdownReport writes a GitHub-Flavored Markdown detection gap analysis
// report to w. The output is suitable for GitHub wikis, READMEs, and docs.
func GapMarkdownReport(w io.Writer, r *gap.GapReport) error {
	// Title.
	fmt.Fprintf(w, "# ThreatEcho — Detection Gap Analysis\n\n")

	agg := r.Aggregate

	// Summary table.
	fmt.Fprintf(w, "## Summary\n\n")
	fmt.Fprintf(w, "| Metric | Value |\n")
	fmt.Fprintf(w, "|--------|-------|\n")
	fmt.Fprintf(w, "| Campaigns Analyzed | %d |\n", agg.TotalCampaigns)
	fmt.Fprintf(w, "| Total Stages | %d |\n", agg.TotalStages)
	fmt.Fprintf(w, "| Unique Techniques | %d |\n", agg.UniqueTechniques)
	fmt.Fprintf(w, "| Unique Detections | %d |\n", agg.UniqueDetections)
	fmt.Fprintf(w, "| Unique Telemetry | %d |\n", agg.UniqueTelemetry)
	fmt.Fprintf(w, "| Risk Score | %.0f/100 |\n\n", r.RiskSummary.Score)

	// Framework coverage.
	fmt.Fprintf(w, "## Framework Coverage\n\n")
	fmt.Fprintf(w, "| Framework | Stages |\n")
	fmt.Fprintf(w, "|-----------|--------|\n")
	if agg.Framework.ATTACKStages > 0 {
		fmt.Fprintf(w, "| MITRE ATT&CK | %d |\n", agg.Framework.ATTACKStages)
	}
	if agg.Framework.ATLASStages > 0 {
		fmt.Fprintf(w, "| MITRE ATLAS | %d |\n", agg.Framework.ATLASStages)
	}
	if agg.Framework.OWASPStages > 0 {
		fmt.Fprintf(w, "| OWASP LLM Top 10 | %d |\n", agg.Framework.OWASPStages)
	}
	fmt.Fprintln(w)

	// ATT&CK tactic coverage.
	if agg.AttackTactics.Total > 0 {
		pct := agg.AttackTactics.Covered * 100 / agg.AttackTactics.Total
		fmt.Fprintf(w, "## ATT&CK Tactic Coverage — %d/%d (%d%%)\n\n",
			agg.AttackTactics.Covered, agg.AttackTactics.Total, pct)
		writeTacticTable(w, agg.AttackTactics)
		fmt.Fprintln(w)
	}

	// ATLAS tactic coverage.
	if agg.AtlasTactics.Total > 0 && (len(agg.AtlasTactics.Details) > 0 || len(agg.AtlasTactics.Missing) > 0) {
		pct := 0
		if agg.AtlasTactics.Total > 0 {
			pct = agg.AtlasTactics.Covered * 100 / agg.AtlasTactics.Total
		}
		fmt.Fprintf(w, "## ATLAS Tactic Coverage — %d/%d (%d%%)\n\n",
			agg.AtlasTactics.Covered, agg.AtlasTactics.Total, pct)
		writeTacticTable(w, agg.AtlasTactics)
		fmt.Fprintln(w)
	}

	// Campaign details.
	if len(r.Campaigns) > 0 {
		fmt.Fprintf(w, "## Campaigns\n\n")
		fmt.Fprintf(w, "| Campaign | Adversary | Stages | Techniques | ATT&CK Coverage | ATLAS Coverage |\n")
		fmt.Fprintf(w, "|----------|-----------|--------|------------|-----------------|----------------|\n")
		for _, c := range r.Campaigns {
			attackCov := "—"
			if c.AttackTactics.Total > 0 {
				attackCov = fmt.Sprintf("%d/%d", c.AttackTactics.Covered, c.AttackTactics.Total)
			}
			atlasCov := "—"
			if c.AtlasTactics.Total > 0 {
				atlasCov = fmt.Sprintf("%d/%d", c.AtlasTactics.Covered, c.AtlasTactics.Total)
			}
			fmt.Fprintf(w, "| %s | %s | %d | %d | %s | %s |\n",
				c.Name, c.Adversary, c.Stages, c.TechniquesUsed, attackCov, atlasCov)
		}
		fmt.Fprintln(w)
	}

	// Gaps by severity.
	fmt.Fprintf(w, "## Detection Gaps\n\n")
	if len(r.Gaps) == 0 {
		fmt.Fprintf(w, "No detection gaps found.\n\n")
	} else {
		fmt.Fprintf(w, "%d issues identified.\n\n", len(r.Gaps))
		writeGapSection(w, r.Gaps, "critical", "Critical")
		writeGapSection(w, r.Gaps, "high", "High")
		writeGapSection(w, r.Gaps, "medium", "Medium")
		writeGapSection(w, r.Gaps, "low", "Low")
	}

	// Risk summary.
	rs := r.RiskSummary
	fmt.Fprintf(w, "## Risk Summary\n\n")
	fmt.Fprintf(w, "| Severity | Count |\n")
	fmt.Fprintf(w, "|----------|-------|\n")
	fmt.Fprintf(w, "| Critical | %d |\n", rs.Critical)
	fmt.Fprintf(w, "| High | %d |\n", rs.High)
	fmt.Fprintf(w, "| Medium | %d |\n", rs.Medium)
	fmt.Fprintf(w, "| Low | %d |\n", rs.Low)
	fmt.Fprintf(w, "| **Total** | **%d** |\n", rs.Total)
	fmt.Fprintf(w, "| **Score** | **%.0f/100** |\n\n", rs.Score)

	// Footer.
	fmt.Fprintf(w, "> Generated by ThreatEcho v%s at %s\n",
		version.Version, r.GeneratedAt.Format("2006-01-02 15:04:05 UTC"))

	return nil
}

// writeTacticTable renders a tactic breakdown as a Markdown table with
// checkbox-style status indicators.
func writeTacticTable(w io.Writer, tb gap.TacticBreakdown) {
	fmt.Fprintf(w, "| Tactic | Status | Stages |\n")
	fmt.Fprintf(w, "|--------|--------|--------|\n")

	for _, d := range tb.Details {
		fmt.Fprintf(w, "| %s | ✓ | %d |\n", d.Name, d.Stages)
	}
	for _, m := range tb.Missing {
		name := m
		// Capitalize missing tactic names for display consistency.
		name = formatTacticShort(name)
		fmt.Fprintf(w, "| %s | ✗ | 0 |\n", name)
	}
}

// writeGapSection writes a severity subsection with each gap as a bullet.
func writeGapSection(w io.Writer, gaps []gap.Gap, risk, label string) {
	var filtered []gap.Gap
	for _, g := range gaps {
		if g.Risk == risk {
			filtered = append(filtered, g)
		}
	}
	if len(filtered) == 0 {
		return
	}

	fmt.Fprintf(w, "### %s\n\n", label)
	for _, g := range filtered {
		if g.Type == gap.GapTacticUncovered {
			fmt.Fprintf(w, "- **Tactic Uncovered** — %s\n", g.Description)
		} else {
			techDisplay := g.Technique
			if g.TechniqueName != "" && g.TechniqueName != g.Technique {
				techDisplay = fmt.Sprintf("%s (%s)", g.Technique, g.TechniqueName)
			}

			parts := []string{
				fmt.Sprintf("**%s**", techDisplay),
			}
			if g.Tactic != "" {
				parts = append(parts, fmt.Sprintf("tactic: %s", g.Tactic))
			}
			if g.CampaignName != "" {
				parts = append(parts, fmt.Sprintf("campaign: %s", g.CampaignName))
			}
			if g.StageID != "" {
				parts = append(parts, fmt.Sprintf("stage: %s", g.StageID))
			}
			parts = append(parts, fmt.Sprintf("type: %s", mdGapTypeLabel(g.Type)))
			if g.Description != "" {
				parts = append(parts, g.Description)
			}
			fmt.Fprintf(w, "- %s\n", strings.Join(parts, " — "))
		}
	}
	fmt.Fprintln(w)
}

// formatTacticShort converts a tactic short name like "initial-access" to
// "Initial Access" for display.
func formatTacticShort(short string) string {
	words := strings.Split(short, "-")
	for i, w := range words {
		if len(w) > 0 {
			words[i] = strings.ToUpper(w[:1]) + w[1:]
		}
	}
	return strings.Join(words, " ")
}

// mdGapTypeLabel returns a human-readable label for a gap type.
func mdGapTypeLabel(t gap.GapType) string {
	switch t {
	case gap.GapDetectionMissing:
		return "Detection Missing"
	case gap.GapTelemetryMissing:
		return "Telemetry Missing"
	case gap.GapTacticUncovered:
		return "Tactic Uncovered"
	default:
		return string(t)
	}
}
