// Copyright (c) 2024-2026 ThreatEcho. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-only
// https://threatecho.com

// Package cli provides shared command-line infrastructure for the ThreatEcho CLI.
//
// It defines typed exit codes (ExitOK, ExitValidation, ExitPolicyDenied,
// ExitRuntime, ExitIO, ExitUsage) for CI pipeline integration, typed error
// constructors ([RuntimeWrap], [IOWrap], [ValidationWrap]), and the [Die]
// function for consistent error reporting.
//
// Shell completion scripts (bash, zsh, fish) are generated by
// [BashCompletion], [ZshCompletion], and [FishCompletion], covering all
// commands, subcommands, and flags.
package cli
