// Copyright (c) 2024-2026 ThreatEcho. All rights reserved.
// SPDX-License-Identifier: AGPL-3.0-only
// https://threatecho.com

package agent

import (
	"encoding/json"
	"fmt"
	"strings"

	"gopkg.in/yaml.v3"
)

// ExportFormat defines supported export output formats.
type ExportFormat string

const (
	// FormatJSON selects JSON as the export output format.
	FormatJSON ExportFormat = "json"
	// FormatYAML selects YAML as the export output format.
	FormatYAML ExportFormat = "yaml"
	// FormatMarkdown selects Markdown as the export output format.
	FormatMarkdown ExportFormat = "markdown"
)

// InventorySnapshot captures the entire inventory state for export,
// including trust analysis and guardrail status.
type InventorySnapshot struct {
	GeneratedBy      string                `json:"generated_by" yaml:"generated_by"`
	AgentCount       int                   `json:"agent_count"  yaml:"agent_count"`
	Agents           []AgentSnapshot       `json:"agents"       yaml:"agents"`
	TrustGraph       *TrustAnalysisSummary `json:"trust_graph,omitempty"  yaml:"trust_graph,omitempty"`
	GuardrailSummary *GuardrailSummary     `json:"guardrail_summary,omitempty" yaml:"guardrail_summary,omitempty"`
}

// AgentSnapshot is an export-friendly view of a single agent.
type AgentSnapshot struct {
	Name         string   `json:"name"         yaml:"name"`
	Type         string   `json:"type"         yaml:"type"`
	Trust        string   `json:"trust"        yaml:"trust"`
	Model        string   `json:"model"        yaml:"model"`
	ToolCount    int      `json:"tool_count"   yaml:"tool_count"`
	Tools        []string `json:"tools"        yaml:"tools"`
	Guardrails   int      `json:"guardrails"   yaml:"guardrails"`
	Capabilities []string `json:"capabilities" yaml:"capabilities"`
	Boundaries   []string `json:"boundaries"   yaml:"boundaries"`
	Risks        []string `json:"risks,omitempty" yaml:"risks,omitempty"`
}

// TrustAnalysisSummary is an export-friendly trust analysis.
type TrustAnalysisSummary struct {
	TotalEdges      int      `json:"total_edges"       yaml:"total_edges"`
	EscalationPaths int      `json:"escalation_paths"  yaml:"escalation_paths"`
	RiskCount       int      `json:"risk_count"        yaml:"risk_count"`
	AdminAgents     []string `json:"admin_agents"      yaml:"admin_agents"`
}

// GuardrailSummary is an export-friendly guardrail overview.
type GuardrailSummary struct {
	TotalGaps         int `json:"total_gaps"          yaml:"total_gaps"`
	CriticalGaps      int `json:"critical_gaps"       yaml:"critical_gaps"`
	FullyCoveredCount int `json:"fully_covered_count" yaml:"fully_covered_count"`
}

// ExportInventory creates a snapshot of the entire inventory for export.
func ExportInventory(inv *Inventory) *InventorySnapshot {
	if inv == nil {
		return &InventorySnapshot{GeneratedBy: "threatecho"}
	}

	snap := &InventorySnapshot{
		GeneratedBy: "threatecho",
		AgentCount:  len(inv.Agents),
	}

	// Run analyses.
	analysis := inv.AnalyzeTrust()
	guardrailReport := inv.AnalyzeAllGuardrails()

	snap.TrustGraph = &TrustAnalysisSummary{
		TotalEdges:      len(analysis.TrustEdges),
		EscalationPaths: len(analysis.EscalationPaths),
		RiskCount:       len(analysis.Risks),
		AdminAgents:     analysis.AdminAgents,
	}

	snap.GuardrailSummary = &GuardrailSummary{
		TotalGaps:         guardrailReport.TotalGaps,
		CriticalGaps:      guardrailReport.CriticalGaps,
		FullyCoveredCount: guardrailReport.FullyCoveredCount,
	}

	// Build risk map from analysis.
	riskMap := make(map[string][]string)
	for _, risk := range analysis.Risks {
		riskMap[risk.AgentName] = append(riskMap[risk.AgentName], risk.Risk)
	}

	for _, a := range inv.Agents {
		as := AgentSnapshot{
			Name:       a.Meta.Name,
			Type:       a.Meta.Type,
			Trust:      a.Trust.Level,
			Model:      a.Meta.Model,
			ToolCount:  len(a.Tools),
			Guardrails: len(a.Guardrails),
			Boundaries: a.Trust.Boundaries,
			Risks:      riskMap[a.Meta.Name],
		}

		for _, t := range a.Tools {
			label := t.Name
			if t.Elevated {
				label += " (elevated)"
			}
			as.Tools = append(as.Tools, label)
		}

		as.Capabilities = activeCapabilities(a)

		snap.Agents = append(snap.Agents, as)
	}

	return snap
}

// ExportJSON marshals the snapshot to JSON.
func ExportJSON(snap *InventorySnapshot) ([]byte, error) {
	return json.MarshalIndent(snap, "", "  ")
}

// ExportYAML marshals the snapshot to YAML.
func ExportYAML(snap *InventorySnapshot) ([]byte, error) {
	return yaml.Marshal(snap)
}

// ExportMarkdown generates a Markdown report from the snapshot.
func ExportMarkdown(snap *InventorySnapshot) string {
	var sb strings.Builder

	sb.WriteString("# Agent Inventory Report\n\n")
	sb.WriteString(fmt.Sprintf("Generated by: %s\n\n", snap.GeneratedBy))
	sb.WriteString(fmt.Sprintf("**Total Agents:** %d\n\n", snap.AgentCount))

	// Trust graph summary.
	if snap.TrustGraph != nil {
		sb.WriteString("## Trust Graph\n\n")
		sb.WriteString(fmt.Sprintf("| Metric | Value |\n"))
		sb.WriteString(fmt.Sprintf("|--------|-------|\n"))
		sb.WriteString(fmt.Sprintf("| Trust Edges | %d |\n", snap.TrustGraph.TotalEdges))
		sb.WriteString(fmt.Sprintf("| Escalation Paths | %d |\n", snap.TrustGraph.EscalationPaths))
		sb.WriteString(fmt.Sprintf("| Risks | %d |\n", snap.TrustGraph.RiskCount))
		if len(snap.TrustGraph.AdminAgents) > 0 {
			sb.WriteString(fmt.Sprintf("| Admin Agents | %s |\n", strings.Join(snap.TrustGraph.AdminAgents, ", ")))
		}
		sb.WriteString("\n")
	}

	// Guardrail summary.
	if snap.GuardrailSummary != nil {
		sb.WriteString("## Guardrail Status\n\n")
		sb.WriteString(fmt.Sprintf("| Metric | Value |\n"))
		sb.WriteString(fmt.Sprintf("|--------|-------|\n"))
		sb.WriteString(fmt.Sprintf("| Total Gaps | %d |\n", snap.GuardrailSummary.TotalGaps))
		sb.WriteString(fmt.Sprintf("| Critical Gaps | %d |\n", snap.GuardrailSummary.CriticalGaps))
		sb.WriteString(fmt.Sprintf("| Fully Covered | %d |\n", snap.GuardrailSummary.FullyCoveredCount))
		sb.WriteString("\n")
	}

	// Individual agents.
	sb.WriteString("## Agents\n\n")
	for _, a := range snap.Agents {
		sb.WriteString(fmt.Sprintf("### %s\n\n", a.Name))
		sb.WriteString(fmt.Sprintf("- **Type:** %s\n", a.Type))
		sb.WriteString(fmt.Sprintf("- **Trust Level:** %s\n", a.Trust))
		if a.Model != "" {
			sb.WriteString(fmt.Sprintf("- **Model:** %s\n", a.Model))
		}
		sb.WriteString(fmt.Sprintf("- **Tools:** %d\n", a.ToolCount))
		sb.WriteString(fmt.Sprintf("- **Guardrails:** %d\n", a.Guardrails))

		if len(a.Capabilities) > 0 {
			sb.WriteString(fmt.Sprintf("- **Capabilities:** %s\n", strings.Join(a.Capabilities, ", ")))
		}
		if len(a.Boundaries) > 0 {
			sb.WriteString(fmt.Sprintf("- **Boundaries:** %s\n", strings.Join(a.Boundaries, ", ")))
		}

		if len(a.Tools) > 0 {
			sb.WriteString("\n**Tools:**\n")
			for _, t := range a.Tools {
				sb.WriteString(fmt.Sprintf("- `%s`\n", t))
			}
		}

		if len(a.Risks) > 0 {
			sb.WriteString("\n**⚠ Risks:**\n")
			for _, r := range a.Risks {
				sb.WriteString(fmt.Sprintf("- %s\n", r))
			}
		}

		sb.WriteString("\n")
	}

	return sb.String()
}
